### PR TITLE
Configure Gitpod

### PR DESCRIPTION
**Pull request by mikenikles**
Hey @brandonroberts, thanks for merging #37 with the upgrades necessary to make my PR here work 🙏.

To experience the best of ephemeral developer environments with Gitpod, could you please enable Prebuilds ([docs](https://www.gitpod.io/docs/prebuilds)) for this repo?

The quickest way is to start at https://gitpod.io/new.

Please let me know what you think of this PR so far. You can test it with the following button:

<a href="https://gitpod.io/#https://github.com/appwrite/demo-todo-with-svelte/pull/38"></a>

### CODE REVIEW

**Comment by brandonroberts** [comment]
@mikenikles the changes so far look good to me. We are working on enabling prebuilds. Should we automatically start the front-end app with the missing environment variables?

**Comment by mikenikles** [comment]
I'd absolutely love to start the front-end app automatically 👍. It does at the moment, but fails because of the missing env vars as you mentioned.

The challenge I had was how to create the app in the backend and get the necessary env variables. Ideally we did that via an API of some sort during the prebuilds.

**Comment by brandonroberts** [comment]
@mikenikles True. If you want to mark this for review, we can go ahead and get it merged, and continue working on getting prebuilds integrated.

**Comment by mikenikles** [comment]
Alright, let's get this merged so I can also publish the new Appwrite & Gitpod guide (what we discussed to be a blog post initially). I'll send you a preview link once it's ready.

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
