### PR TITLE
Add deploy to heroku button

### LINKED ISSUE #33: 🚀 Feature: Add deploy to heroku button
### 🔖 Feature description

Underneath the static hosting providers' buttons: https://github.com/appwrite/demo-todo-with-svelte#deploy-to-a-static-hosting-provider, there should be another button for Heroku.

### 🎤 Pitch

I usually deploy my applications to Heroku, and it is best to provide another option to the hosting providers so others who don't use Vercel or something else can also deploy this todo demo app.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Yash-Singh1**
Fixes #33

### CODE REVIEW

**Comment by Yash-Singh1** [comment]
@eldadfux @PineappleIOnic, Could you review this PR for the Hacktoberfest?

**Comment by Yash-Singh1** [comment]
@christyjacob4 Could you have a look at my PR?

**Review by christyjacob4 — CHANGES_REQUESTED** [review]
@Yash-Singh1  please share a gif/ video of your implementation. we'd like to see this working 🙂

**Comment by Yash-Singh1** [comment]
This video is from the `Yash-Singh1/demo-todo-with-svelte:deployToHeroku` branch.

https://user-images.githubusercontent.com/53054099/143780423-7e5348b2-adc7-43f4-bc42-e9c6f7aaeccf.mp4

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on discord to claim your Hacktoberfest swag.

As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord so that we can add you as a contributor to our organization.

Once added, you can change your membership visibility settings, so your new Appwrite membership badge will show up on your personal GitHub profile.

**Pull request merged**
