### PR TITLE
Upgraded issue templates to use GitHub issue forms #21

### PR DESCRIPTION
**Pull request by Vidushi-Gupta**
Please let me know of any changes that need to be incorporated. Thank you for letting me work on this!
Best,
Vidushi

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@Vidushi-Gupta thank you for great work. We have made some changes to our template. Please update accordingly.

**Review by lohanidamodar — CHANGES_REQUESTED** [review]
@Vidushi-Gupta please review our updated templates and make the necessary changes (for example the format of code of conduct field), to make it consistent across our repositories.

**Comment by Vidushi-Gupta** [comment]
Please let me know if I still missed out on something. Thanks and regards

**Comment by Meldiron** [comment]
Can we please keep validate.yml? I don't think that needs to be removed. Otherwise everything seems correct to me 😎

**Pull request closed without merging**
